import type { EnemyId } from '../core/balance';

/**
 * Animated monster art: 4-direction walk sheets in public/monsters/<key>.png (CraftPix packs, see SOURCE.txt there).
 * Each sheet is 4 rows of `cols` square frames of `frame` px: rows run down, up, left, right ('DULR') or
 * down, left, right, up ('DLRU'). `box` is the character's bounding box within a frame [x, y, w, h], used to
 * size and centre it whatever padding the pack leaves.
 */
export interface MonsterSheet {
  frame: number;
  cols: number;
  order: 'DULR' | 'DLRU';
  box: [number, number, number, number];
}

export const SHEETS: Record<string, MonsterSheet> = {
  'slime-green': { frame: 64, cols: 8, order: 'DULR', box: [15, 17, 34, 23] },
  'slime-lava': { frame: 64, cols: 8, order: 'DULR', box: [15, 4, 34, 36] },
  'orc-green': { frame: 64, cols: 6, order: 'DULR', box: [10, 13, 44, 31] },
  'orc-teal': { frame: 64, cols: 6, order: 'DULR', box: [10, 11, 44, 33] },
  'slime-king': { frame: 128, cols: 8, order: 'DULR', box: [35, 37, 58, 40] },
  'slime-magma': { frame: 64, cols: 8, order: 'DULR', box: [8, 8, 48, 32] },
  'slime-shadow': { frame: 64, cols: 8, order: 'DULR', box: [14, 17, 35, 23] },
  'slime-umbral': { frame: 64, cols: 8, order: 'DULR', box: [15, 14, 34, 26] },
  'slime-cloud': { frame: 128, cols: 8, order: 'DULR', box: [35, 37, 58, 42] },
  'slime-frost': { frame: 64, cols: 8, order: 'DULR', box: [15, 15, 34, 25] },
  'ent-twig': { frame: 128, cols: 6, order: 'DULR', box: [44, 30, 39, 50] },
  'ent-leafy': { frame: 128, cols: 6, order: 'DULR', box: [33, 9, 61, 71] },
  'goblin': { frame: 64, cols: 6, order: 'DULR', box: [15, 16, 30, 31] },
  'mushroom-red': { frame: 64, cols: 6, order: 'DULR', box: [11, 12, 42, 31] },
  'plant-trap': { frame: 64, cols: 6, order: 'DULR', box: [8, 13, 48, 38] },
  'golem-stone': { frame: 128, cols: 8, order: 'DULR', box: [40, 39, 48, 37] },
  'golem-crystal': { frame: 128, cols: 8, order: 'DULR', box: [36, 32, 55, 44] },
  'golem-ice': { frame: 128, cols: 8, order: 'DULR', box: [37, 24, 53, 52] },
  'golem-ore': { frame: 128, cols: 8, order: 'DULR', box: [40, 39, 48, 37] },
  'golem-venom': { frame: 128, cols: 8, order: 'DULR', box: [40, 39, 48, 37] },
  'golem-lava': { frame: 128, cols: 8, order: 'DULR', box: [37, 24, 53, 52] },
  'golem-void': { frame: 128, cols: 8, order: 'DULR', box: [36, 32, 55, 44] },
  'skeleton': { frame: 64, cols: 6, order: 'DULR', box: [13, 18, 38, 23] },
  'skeleton-knight': { frame: 64, cols: 6, order: 'DULR', box: [12, 18, 40, 23] },
  'skeleton-king': { frame: 64, cols: 6, order: 'DULR', box: [13, 14, 38, 27] },
  'zombie': { frame: 64, cols: 6, order: 'DULR', box: [19, 15, 26, 27] },
  'mummy': { frame: 64, cols: 6, order: 'DULR', box: [19, 15, 26, 27] },
  'ghost-pale': { frame: 64, cols: 6, order: 'DULR', box: [17, 8, 30, 32] },
  'ghost-dark': { frame: 64, cols: 6, order: 'DULR', box: [14, 7, 36, 33] },
  'ghost-red': { frame: 64, cols: 6, order: 'DULR', box: [10, 5, 44, 36] },
  'lich': { frame: 64, cols: 6, order: 'DULR', box: [18, 9, 27, 37] },
  'lich-dark': { frame: 64, cols: 6, order: 'DULR', box: [16, 7, 29, 39] },
  'lich-gold': { frame: 64, cols: 6, order: 'DULR', box: [16, 5, 31, 41] },
  'mage-purple': { frame: 64, cols: 6, order: 'DLRU', box: [13, 17, 38, 27] },
  'mage-green': { frame: 64, cols: 6, order: 'DLRU', box: [15, 14, 35, 30] },
  'knight-steel': { frame: 64, cols: 6, order: 'DLRU', box: [17, 18, 30, 30] },
  'knight-sky': { frame: 64, cols: 6, order: 'DLRU', box: [13, 15, 38, 30] },
  'knight-dark': { frame: 64, cols: 6, order: 'DLRU', box: [12, 14, 40, 30] },
  'knight-gold': { frame: 64, cols: 6, order: 'DLRU', box: [10, 14, 44, 30] },
  'beholder-pale': { frame: 64, cols: 8, order: 'DULR', box: [11, 5, 43, 48] },
  'beholder-red': { frame: 64, cols: 8, order: 'DULR', box: [11, 6, 44, 49] },
  'beholder-dark': { frame: 64, cols: 8, order: 'DULR', box: [2, 0, 59, 57] },
  'rat-black': { frame: 128, cols: 6, order: 'DULR', box: [30, 44, 70, 44] },
  'rat-mite': { frame: 128, cols: 6, order: 'DULR', box: [30, 45, 70, 43] },
  'imp-red': { frame: 64, cols: 6, order: 'DULR', box: [13, 14, 38, 30] },
  'lizard-green': { frame: 64, cols: 6, order: 'DULR', box: [15, 3, 34, 40] },
  'lizard-red': { frame: 64, cols: 6, order: 'DULR', box: [15, 2, 34, 41] },
  'gnoll': { frame: 64, cols: 6, order: 'DULR', box: [14, 10, 36, 35] },
  'gnoll-dark': { frame: 64, cols: 6, order: 'DULR', box: [14, 10, 36, 35] },
  'demon-red': { frame: 128, cols: 6, order: 'DULR', box: [34, 34, 59, 61] },
  'demon-purple': { frame: 128, cols: 6, order: 'DULR', box: [34, 34, 59, 61] },
  'vampire-red': { frame: 64, cols: 6, order: 'DULR', box: [12, 16, 40, 29] },
};

/** Which sheet each monster walks with (as a Guardian too, drawn bigger). Monsters without one keep their shape. */
export const MONSTER_SHEETS: Partial<Record<EnemyId, string>> = {
  greenSlime: 'slime-green',
  kingSlime: 'slime-king',
  twiggling: 'ent-twig',
  goblin: 'goblin',
  toadstool: 'mushroom-red',
  manTrap: 'plant-trap',
  treant: 'ent-leafy',
  stoneGolem: 'golem-stone',
  skeleton: 'skeleton',
  zombie: 'zombie',
  cultist: 'mage-purple',
  graveWraith: 'ghost-red',
  skeletonKing: 'skeleton-king',
  boneKnight: 'skeleton-knight',
  possessedArmor: 'knight-steel',
  mummy: 'mummy',
  necromancer: 'mage-green',
  awokenLich: 'lich-gold',
  gloomcrawler: 'rat-black',
  shadowWisp: 'ghost-dark',
  gazingEye: 'beholder-pale',
  umbralOoze: 'slime-umbral',
  deepLurker: 'gnoll-dark',
  beholdenWatcher: 'beholder-dark',
  imp: 'imp-red',
  magmaSlime: 'slime-lava',
  cometWisp: 'slime-magma',
  salamander: 'lizard-red',
  oreGolem: 'golem-ore',
  geodeGolem: 'golem-crystal',
  demonLord: 'demon-red',
  kobold: 'gnoll',
  basilisk: 'lizard-green',
  lavaGolem: 'golem-lava',
  venomGolem: 'golem-venom',
  caveTroll: 'orc-green',
  frostGiant: 'orc-teal',
  golem: 'golem-ice',
  wraith: 'ghost-pale',
  frostSprite: 'slime-frost',
  glacialGolem: 'golem-ice',
  crystalGolem: 'golem-crystal',
  cloudling: 'slime-cloud',
  skyKnight: 'knight-sky',
  valkyrie: 'knight-gold',
  rockMite: 'rat-mite',
  astralSentinel: 'knight-gold',
  meteorGolem: 'golem-lava',
  shadowSlime: 'slime-shadow',
  horror: 'demon-purple',
  lich: 'lich',
  shade: 'lich-dark',
  watcher: 'beholder-red',
  darkKnight: 'knight-dark',
  succubus: 'vampire-red',
  voidGolem: 'golem-void',
};
