import type { EnemyId } from '../core/balance';

/**
 * Animated monster art: walk sheets in public/monsters/<key>.png (CraftPix packs, see SOURCE.txt there), of
 * `cols` square frames of `frame` px. Top-down sheets have 4 rows, running down, up, left, right ('DULR') or
 * down, left, right, up ('DLRU'); side-view sheets ('SIDE') are one row facing right (or left, `faces: 'L'`), mirrored to face the other way.
 * `box` is the character's bounding box within a frame [x, y, w, h], used to size and centre it whatever
 * padding the pack leaves.
 */
export interface MonsterSheet {
  frame: number;
  cols: number;
  order: 'DULR' | 'DLRU' | 'SIDE';
  /** Which way a side-view sheet's art faces ('R' unless set); it's mirrored to face the other way. */
  faces?: 'L' | 'R';
  box: [number, number, number, number];
}

export const SHEETS: Record<string, MonsterSheet> = {
  'slime-green': { frame: 64, cols: 8, order: 'DULR', box: [15, 17, 34, 23] },
  'slime-lava': { frame: 64, cols: 8, order: 'DULR', box: [15, 4, 34, 36] },
  'orc-green': { frame: 64, cols: 6, order: 'DULR', box: [10, 13, 44, 31] },
  'orc-teal': { frame: 64, cols: 6, order: 'DULR', box: [10, 11, 44, 33] },
  'slime-king': { frame: 128, cols: 8, order: 'DULR', box: [35, 37, 58, 40] },
  'slime-magma': { frame: 64, cols: 8, order: 'DULR', box: [8, 8, 48, 32] },
  'slime-shadow': { frame: 64, cols: 8, order: 'DULR', box: [14, 17, 35, 23] },
  'slime-umbral': { frame: 64, cols: 8, order: 'DULR', box: [15, 14, 34, 26] },
  'slime-cloud': { frame: 128, cols: 8, order: 'DULR', box: [35, 37, 58, 42] },
  'slime-frost': { frame: 64, cols: 8, order: 'DULR', box: [15, 15, 34, 25] },
  'ent-twig': { frame: 128, cols: 6, order: 'DULR', box: [44, 30, 39, 50] },
  'ent-leafy': { frame: 128, cols: 6, order: 'DULR', box: [33, 9, 61, 71] },
  'goblin': { frame: 64, cols: 6, order: 'DULR', box: [15, 16, 30, 31] },
  'mushroom-red': { frame: 64, cols: 6, order: 'DULR', box: [11, 12, 42, 31] },
  'plant-trap': { frame: 64, cols: 6, order: 'DULR', box: [8, 13, 48, 38] },
  'golem-stone': { frame: 128, cols: 8, order: 'DULR', box: [40, 39, 48, 37] },
  'golem-crystal': { frame: 128, cols: 8, order: 'DULR', box: [36, 32, 55, 44] },
  'golem-ice': { frame: 128, cols: 8, order: 'DULR', box: [37, 24, 53, 52] },
  'golem-ore': { frame: 128, cols: 8, order: 'DULR', box: [40, 39, 48, 37] },
  'golem-venom': { frame: 128, cols: 8, order: 'DULR', box: [40, 39, 48, 37] },
  'golem-lava': { frame: 128, cols: 8, order: 'DULR', box: [37, 24, 53, 52] },
  'golem-void': { frame: 128, cols: 8, order: 'DULR', box: [36, 32, 55, 44] },
  'skeleton': { frame: 64, cols: 6, order: 'DULR', box: [13, 18, 38, 23] },
  'skeleton-knight': { frame: 64, cols: 6, order: 'DULR', box: [12, 18, 40, 23] },
  'skeleton-king': { frame: 64, cols: 6, order: 'DULR', box: [13, 14, 38, 27] },
  'zombie': { frame: 64, cols: 6, order: 'DULR', box: [19, 15, 26, 27] },
  'mummy': { frame: 64, cols: 6, order: 'DULR', box: [19, 15, 26, 27] },
  'ghost-pale': { frame: 64, cols: 6, order: 'DULR', box: [17, 8, 30, 32] },
  'ghost-dark': { frame: 64, cols: 6, order: 'DULR', box: [14, 7, 36, 33] },
  'ghost-red': { frame: 64, cols: 6, order: 'DULR', box: [10, 5, 44, 36] },
  'lich': { frame: 64, cols: 6, order: 'DULR', box: [18, 9, 27, 37] },
  'lich-dark': { frame: 64, cols: 6, order: 'DULR', box: [16, 7, 29, 39] },
  'lich-gold': { frame: 64, cols: 6, order: 'DULR', box: [16, 5, 31, 41] },
  'mage-purple': { frame: 64, cols: 6, order: 'DLRU', box: [13, 17, 38, 27] },
  'mage-green': { frame: 64, cols: 6, order: 'DLRU', box: [15, 14, 35, 30] },
  'knight-steel': { frame: 64, cols: 6, order: 'DLRU', box: [17, 18, 30, 30] },
  'knight-sky': { frame: 64, cols: 6, order: 'DLRU', box: [13, 15, 38, 30] },
  'knight-dark': { frame: 64, cols: 6, order: 'DLRU', box: [12, 14, 40, 30] },
  'knight-gold': { frame: 64, cols: 6, order: 'DLRU', box: [10, 14, 44, 30] },
  'beholder-pale': { frame: 64, cols: 8, order: 'DULR', box: [11, 5, 43, 48] },
  'beholder-red': { frame: 64, cols: 8, order: 'DULR', box: [11, 6, 44, 49] },
  'beholder-dark': { frame: 64, cols: 8, order: 'DULR', box: [2, 0, 59, 57] },
  'rat-black': { frame: 128, cols: 6, order: 'DULR', box: [30, 44, 70, 44] },
  'rat-mite': { frame: 128, cols: 6, order: 'DULR', box: [30, 45, 70, 43] },
  'imp-red': { frame: 64, cols: 6, order: 'DULR', box: [13, 14, 38, 30] },
  'lizard-green': { frame: 64, cols: 6, order: 'DULR', box: [15, 3, 34, 40] },
  'lizard-red': { frame: 64, cols: 6, order: 'DULR', box: [15, 2, 34, 41] },
  'gnoll': { frame: 64, cols: 6, order: 'DULR', box: [14, 10, 36, 35] },
  'gnoll-dark': { frame: 64, cols: 6, order: 'DULR', box: [14, 10, 36, 35] },
  'demon-red': { frame: 128, cols: 6, order: 'DULR', box: [34, 34, 59, 61] },
  'demon-purple': { frame: 128, cols: 6, order: 'DULR', box: [34, 34, 59, 61] },
  'vampire-red': { frame: 64, cols: 6, order: 'DULR', box: [12, 16, 40, 29] },
  'wolf-grey': { frame: 48, cols: 6, order: 'SIDE', faces: 'L', box: [0, 22, 48, 26] },
  'wolf-ice': { frame: 48, cols: 6, order: 'SIDE', faces: 'L', box: [0, 22, 48, 26] },
  'bear-brown': { frame: 48, cols: 6, order: 'SIDE', box: [5, 24, 43, 24] },
  'yeti': { frame: 72, cols: 6, order: 'SIDE', box: [5, 42, 51, 30] },
  'pixie': { frame: 48, cols: 4, order: 'SIDE', box: [18, 17, 25, 20] },
  'pixie-queen': { frame: 48, cols: 4, order: 'SIDE', box: [18, 17, 25, 20] },
  'unicorn': { frame: 72, cols: 6, order: 'SIDE', box: [0, 37, 61, 35] },
  'bat': { frame: 48, cols: 4, order: 'SIDE', faces: 'L', box: [10, 21, 36, 22] },
  'crow': { frame: 48, cols: 4, order: 'SIDE', faces: 'L', box: [17, 23, 30, 24] },
  'puppet': { frame: 48, cols: 6, order: 'SIDE', box: [17, 10, 28, 38] },
  'duskmoth': { frame: 48, cols: 4, order: 'SIDE', faces: 'L', box: [5, 8, 43, 33] },
  'fire-beetle': { frame: 48, cols: 4, order: 'SIDE', faces: 'L', box: [8, 31, 38, 17] },
  'hellhound': { frame: 128, cols: 9, order: 'SIDE', box: [15, 75, 93, 53] },
  'chimera': { frame: 72, cols: 6, order: 'SIDE', faces: 'L', box: [21, 30, 50, 42] },
  'drake-fire': { frame: 256, cols: 12, order: 'SIDE', box: [14, 172, 213, 84] },
  'wyvern-ice': { frame: 256, cols: 12, order: 'SIDE', box: [1, 0, 240, 256] },
  'star-eater': { frame: 256, cols: 12, order: 'SIDE', box: [0, 0, 256, 256] },
  'void-wyrm': { frame: 256, cols: 12, order: 'SIDE', box: [7, 0, 240, 256] },
  'harpy': { frame: 128, cols: 8, order: 'SIDE', box: [18, 38, 73, 90] },
  'snow-owl': { frame: 32, cols: 6, order: 'DULR', box: [0, 1, 31, 27] },
  'griffin': { frame: 48, cols: 4, order: 'SIDE', faces: 'L', box: [10, 17, 38, 29] },
  'thunderbird': { frame: 48, cols: 4, order: 'SIDE', faces: 'L', box: [10, 17, 38, 29] },
  'golem-sky': { frame: 128, cols: 7, order: 'SIDE', box: [47, 50, 37, 78] },
  'golem-storm': { frame: 128, cols: 8, order: 'SIDE', box: [25, 71, 56, 57] },
  'storm-titan': { frame: 128, cols: 8, order: 'SIDE', box: [24, 54, 56, 74] },
  'meteorite': { frame: 72, cols: 4, order: 'SIDE', box: [25, 20, 47, 51] },
  'behemoth': { frame: 72, cols: 6, order: 'SIDE', faces: 'L', box: [12, 29, 59, 43] },
  'time-eater': { frame: 256, cols: 8, order: 'SIDE', box: [82, 132, 122, 124] },
};

/** Which sheet each monster walks with (as a Guardian too, drawn bigger). Monsters without one keep their shape. */
export const MONSTER_SHEETS: Partial<Record<EnemyId, string>> = {
  greenSlime: 'slime-green',
  kingSlime: 'slime-king',
  twiggling: 'ent-twig',
  goblin: 'goblin',
  toadstool: 'mushroom-red',
  manTrap: 'plant-trap',
  treant: 'ent-leafy',
  stoneGolem: 'golem-stone',
  skeleton: 'skeleton',
  zombie: 'zombie',
  cultist: 'mage-purple',
  graveWraith: 'ghost-red',
  skeletonKing: 'skeleton-king',
  boneKnight: 'skeleton-knight',
  possessedArmor: 'knight-steel',
  mummy: 'mummy',
  necromancer: 'mage-green',
  awokenLich: 'lich-gold',
  gloomcrawler: 'rat-black',
  shadowWisp: 'ghost-dark',
  gazingEye: 'beholder-pale',
  umbralOoze: 'slime-umbral',
  deepLurker: 'gnoll-dark',
  beholdenWatcher: 'beholder-dark',
  imp: 'imp-red',
  magmaSlime: 'slime-lava',
  cometWisp: 'slime-magma',
  salamander: 'lizard-red',
  oreGolem: 'golem-ore',
  geodeGolem: 'golem-crystal',
  demonLord: 'demon-red',
  kobold: 'gnoll',
  basilisk: 'lizard-green',
  lavaGolem: 'golem-lava',
  venomGolem: 'golem-venom',
  caveTroll: 'orc-green',
  frostGiant: 'orc-teal',
  golem: 'golem-ice',
  wraith: 'ghost-pale',
  frostSprite: 'slime-frost',
  glacialGolem: 'golem-ice',
  crystalGolem: 'golem-crystal',
  cloudling: 'slime-cloud',
  skyKnight: 'knight-sky',
  valkyrie: 'knight-gold',
  rockMite: 'rat-mite',
  astralSentinel: 'knight-gold',
  meteorGolem: 'golem-lava',
  shadowSlime: 'slime-shadow',
  horror: 'demon-purple',
  lich: 'lich',
  shade: 'lich-dark',
  watcher: 'beholder-red',
  darkKnight: 'knight-dark',
  succubus: 'vampire-red',
  voidGolem: 'golem-void',
  wolf: 'wolf-grey',
  brownBear: 'bear-brown',
  pixie: 'pixie',
  pixieQueen: 'pixie-queen',
  unicorn: 'unicorn',
  bat: 'bat',
  crow: 'crow',
  puppet: 'puppet',
  duskmoth: 'duskmoth',
  beetle: 'fire-beetle',
  hellhound: 'hellhound',
  fireDrake: 'drake-fire',
  iceWolf: 'wolf-ice',
  yeti: 'yeti',
  harpy: 'harpy',
  snowOwl: 'snow-owl',
  griffin: 'griffin',
  iceWyvern: 'wyvern-ice',
  skyGolem: 'golem-sky',
  thunderbird: 'thunderbird',
  stormTitan: 'storm-titan',
  stormGolem: 'golem-storm',
  meteorite: 'meteorite',
  starEater: 'star-eater',
  chimera: 'chimera',
  voidWyrm: 'void-wyrm',
  behemoth: 'behemoth',
  timeEater: 'time-eater',
};

/** The row of a sheet that faces a direction (a side-view sheet has only one; it's mirrored to face left). */
export function sheetRow(sh: MonsterSheet, dir: 'D' | 'U' | 'L' | 'R'): number {
  return sh.order === 'SIDE' ? 0 : sh.order.indexOf(dir);
}

/** Whether a side-view sheet must be mirrored to face a heading (dx < 0 = moving left). */
export function sideFlip(sh: MonsterSheet, dx: number): boolean {
  return sh.order === 'SIDE' && (sh.faces === 'L' ? dx > 0 : dx < 0);
}
