/**
 * The bulk of each area's gear, one line per item: name, icon, type, damage type and recipe. balance.ts turns
 * these into full GearDefs: weapon damage comes from the tier (worked out from the recipe, as for all gear),
 * armor stats from its kind and tier, accessory stats from the stats named here (scaled by tier), rarity from
 * the area (`top` items, made with the area's rarest material, are one rarity higher) and status chance from
 * the damage type. Anything here can be swapped for a hand-written entry in GEAR when an item needs more.
 *
 * Progression: the Wandering Woods have melee, bows and a couple of wands (in GEAR); the Fey Grove opens up
 * magic (scepters, staffs, focuses, tomes, robes); accessories start in the Restless Graveyard (with hammers);
 * firearms (pistols, rifles, repeaters) in the Shadowy Depths, with Wilhelm. Each area has more items than the
 * last, as players stay longer in later areas.
 */

export type CatalogDamage = 'physical' | 'fire' | 'acid' | 'frost' | 'radiant' | 'poison' | 'arcane' | 'decay' | 'lightning' | 'void';
export type CatalogWeapon = 'tome' | 'dagger' | 'sword' | 'glaive' | 'spear' | 'hammer' | 'shortbow' | 'longbow' | 'crossbow' | 'pistol' | 'rifle' | 'repeater' | 'wand' | 'staff' | 'focus' | 'scepter';
export type CatalogArmor = 'light' | 'heavy' | 'robe' | 'shield';
/** Stats an accessory can carry (values come from the tier). */
export type CatalogAccStat = 'damage' | 'rate' | 'crit' | 'gold' | 'drops' | 'range' | 'radius' | 'stun';
export type CatalogArchetype = 'slime' | 'beast' | 'undead' | 'demon' | 'elemental' | 'humanoid' | 'plant' | 'dragon' | 'construct';

export type CatalogSpec<I extends string = string> =
  | { id: I; name: string; icon: string; area: string; type: 'weapon'; cls: CatalogWeapon; dmg: CatalogDamage; recipe: Record<string, number>; top?: boolean }
  | { id: I; name: string; icon: string; area: string; type: 'armor'; armor: CatalogArmor; recipe: Record<string, number>; top?: boolean }
  | { id: I; name: string; icon: string; area: string; type: 'accessory'; stats: CatalogAccStat[]; bane?: CatalogArchetype; recipe: Record<string, number>; top?: boolean };

let area = '';
const w = <I extends string>(id: I, name: string, icon: string, cls: CatalogWeapon, dmg: CatalogDamage, recipe: Record<string, number>, top = false) =>
  ({ id, name, icon, area, type: 'weapon', cls, dmg, recipe, top }) as const;
const a = <I extends string>(id: I, name: string, icon: string, armor: CatalogArmor, recipe: Record<string, number>, top = false) =>
  ({ id, name, icon, area, type: 'armor', armor, recipe, top }) as const;
const x = <I extends string>(id: I, name: string, icon: string, stats: CatalogAccStat[], recipe: Record<string, number>, bane?: CatalogArchetype, top = false) =>
  ({ id, name, icon, area, type: 'accessory', stats, bane, recipe, top }) as const;
const at = (id: string) => ((area = id), []);

export const GEAR_CATALOG = [
  // ---- Fey Grove: magic opens up (no accessories yet) ----
  ...at('glade'),
  w('sporeWand', 'Spore Wand', '🍄', 'wand', 'poison', { spore: 10, twig: 6 }),
  w('pixieWand', 'Pixie Wand', '✨', 'wand', 'arcane', { dust: 10, spore: 4 }),
  w('mossStaff', 'Mossy Staff', '🌿', 'staff', 'poison', { sap: 8, spore: 6 }),
  w('unicornStaff', 'Unicorn Staff', '🦄', 'staff', 'radiant', { unicornHorn: 6, sap: 6 }),
  w('dewFocus', 'Dewdrop Focus', '💧', 'focus', 'arcane', { dust: 8, sap: 5 }),
  w('bloomTome', 'Tome of Blooms', '📗', 'tome', 'poison', { thorn: 8, spore: 8 }),
  w('thornDagger', 'Thorn Dagger', '🗡️', 'dagger', 'poison', { thorn: 8, beastBone: 4 }),
  w('hornSword', 'Unicorn Blade', '⚔️', 'sword', 'radiant', { unicornHorn: 6, enchantedBone: 6 }),
  w('sapBow', 'Sapwood Bow', '🏹', 'shortbow', 'physical', { sap: 8, twig: 6 }),
  w('queenScepter', "Queen's Scepter", '👑', 'scepter', 'arcane', { regalEssence: 3, dust: 10 }, true),
  a('fairyRobe', 'Fairy-Silk Robe', '👘', 'robe', { dust: 10, spore: 6 }),
  a('capRobe', 'Mushroom-Cap Robe', '🥻', 'robe', { spore: 12, sap: 4 }),
  a('barkPlate', 'Bark Plate', '🪵', 'heavy', { sap: 10, enchantedBone: 5 }),
  a('regalGown', 'Regal Gown', '👗', 'robe', { regalEssence: 2, dust: 8, unicornHorn: 4 }, true),
  w('fungalScepter', 'Fungal Scepter', '🍄', 'scepter', 'poison', { spore: 10, sap: 4 }),
  w('pixieLongbow', 'Pixie Longbow', '🏹', 'longbow', 'arcane', { dust: 8, twig: 8 }),

  // ---- Restless Graveyard: accessories start here, and hammers ----
  ...at('graveyard'),
  w('graveDagger', 'Grave Dagger', '🗡️', 'dagger', 'decay', { bone: 8, flesh: 6 }),
  w('batBow', 'Batwing Bow', '🦇', 'shortbow', 'physical', { wing: 10, bone: 4 }),
  w('sacredWand', 'Sacred Wand', '🕯️', 'wand', 'radiant', { sacredText: 8, wing: 4 }),
  w('wispFocus', 'Wisp Lantern', '🏮', 'focus', 'arcane', { nightmareWisp: 8, robePiece: 4 }),
  w('vampireBlade', 'Vampire Blade', '⚔️', 'sword', 'decay', { vampEssence: 8, bone: 6 }),
  w('kingsMaul', "Skeleton King's Maul", '🔨', 'hammer', 'physical', { calciumCrystal: 3, bone: 12 }, true),
  a('graveShroud', 'Grave Shroud', '🧥', 'light', { robePiece: 8, wing: 5 }),
  a('calciumPlate', 'Calcium Plate', '🛡️', 'heavy', { calciumCrystal: 2, bone: 12, flesh: 4 }, true),
  x('boneCharm', 'Bone Charm', '🦴', ['crit'], { bone: 10, wing: 4 }),
  x('bloodPendant', 'Blood Pendant', '🩸', ['rate'], { vampEssence: 8, bone: 4 }),
  w('nightmareLongbow', 'Nightmare Longbow', '🏹', 'longbow', 'decay', { nightmareWisp: 8, wing: 6 }),
  w('cultistTome', 'Cultist Tome', '📕', 'tome', 'decay', { sacredText: 10, robePiece: 5 }),
  a('vampireCape', 'Vampire Cape', '🧛', 'light', { vampEssence: 8, wing: 6 }),
  x('graveLantern', 'Grave Lantern', '🏮', ['radius'], { nightmareWisp: 8, bone: 4 }),

  // ---- Forbidden Crypt: more of everything ----
  ...at('crypt'),
  w('crowBow', 'Crowfeather Bow', '🪶', 'shortbow', 'physical', { undeadFeather: 10, string: 4 }),
  w('stringCrossbow', 'Puppet-String Crossbow', '🎯', 'crossbow', 'physical', { string: 10, enchantedScrap: 4 }),
  w('cryptBlade', 'Crypt Blade', '⚔️', 'sword', 'decay', { enchantedScrap: 10, wrap: 4 }),
  w('cursedDagger', 'Cursed Dagger', '🗡️', 'dagger', 'decay', { enchantedScrap: 8, undeadFeather: 5 }),
  w('sarcophagusHammer', 'Sarcophagus Hammer', '🔨', 'hammer', 'physical', { enchantedScrap: 12, wrap: 6 }),
  w('tombSpear', 'Tomb Spear', '🔱', 'spear', 'physical', { enchantedScrap: 10, string: 5 }),
  w('forbiddenWand', 'Forbidden Wand', '📜', 'wand', 'decay', { grave: 8, wrap: 4 }),
  w('hexStaff', 'Hex Staff', '🪄', 'staff', 'arcane', { grave: 10, string: 5 }),
  w('wrappingTome', 'Tome of Wrappings', '📕', 'tome', 'decay', { wrap: 10, grave: 5 }),
  w('phylactery', 'Phylactery Focus', '⚱️', 'focus', 'decay', { eldritchText: 2, grave: 8 }, true),
  w('eldritchScepter', 'Eldritch Scepter', '🔮', 'scepter', 'arcane', { eldritchText: 3, grave: 8, undeadFeather: 5 }, true),
  a('crowCloak', 'Crow-Feather Cloak', '🧥', 'light', { undeadFeather: 10, wrap: 5 }),
  a('hauntedShield', 'Haunted Shield', '🛡️', 'shield', { enchantedScrap: 10, string: 5 }),
  a('lichRobe', 'Lich Robe', '🥻', 'robe', { eldritchText: 2, wrap: 10 }, true),
  x('marionetteRing', 'Marionette Ring', '💍', ['rate'], { string: 8, enchantedScrap: 4 }),
  x('cryptKey', 'Crypt Key', '🗝️', ['drops'], { enchantedScrap: 8, grave: 4 }),
  x('deathMask', 'Death Mask', '🎭', ['crit'], { wrap: 8, undeadFeather: 5 }),
  x('wardstone', 'Wardstone', '🪬', [], { grave: 6, enchantedScrap: 6 }, 'undead'),
  w('mummyGlaive', 'Mummy Glaive', '🪓', 'glaive', 'decay', { wrap: 10, enchantedScrap: 6 }),
  w('ravenWand', 'Raven Wand', '🪶', 'wand', 'arcane', { undeadFeather: 8, grave: 4 }),
  a('boneKnightPlate', 'Bone Knight Plate', '🛡️', 'heavy', { enchantedScrap: 12, undeadFeather: 4 }),

  // ---- Shadowy Depths: firearms start here, with Wilhelm ----
  ...at('depths'),
  w('shadowPistol', 'Shadow Pistol', '🔫', 'pistol', 'void', { shadowWisp: 8, darkClaw: 5 }),
  w('pearlPistol', 'Pearl Pistol', '🔫', 'pistol', 'arcane', { umbra: 6, gloom: 6 }),
  w('gloomRifle', 'Gloomstalker Rifle', '🎯', 'rifle', 'physical', { darkClaw: 10, gloom: 5 }),
  w('eyeRifle', "Watcher's Rifle", '👁️', 'rifle', 'arcane', { umbralEye: 8, umbra: 4 }),
  w('oozeRepeater', 'Ooze Repeater', '🔫', 'repeater', 'acid', { umbralSlime: 10, darkClaw: 5 }),
  w('gloomclawDagger', 'Gloomclaw Dagger', '🗡️', 'dagger', 'physical', { darkClaw: 10, gloom: 4 }),
  w('duskBlade', 'Dusk Blade', '⚔️', 'sword', 'void', { shadowWisp: 10, darkClaw: 4 }),
  w('lurkerSpear', 'Lurker Spear', '🔱', 'spear', 'acid', { umbra: 6, umbralSlime: 6 }),
  w('abyssHammer', 'Abyssal Hammer', '🔨', 'hammer', 'void', { umbra: 8, darkClaw: 8 }),
  w('mothLongbow', 'Duskmoth Longbow', '🏹', 'longbow', 'physical', { gloom: 10, darkClaw: 4 }),
  w('shadowWand', 'Shadow Wand', '🪄', 'wand', 'void', { shadowWisp: 8, gloom: 4 }),
  w('oozeStaff', 'Ooze Staff', '🧪', 'staff', 'acid', { umbralSlime: 10, shadowWisp: 4 }),
  w('shadowTome', 'Tome of Shadows', '📓', 'tome', 'void', { shadowWisp: 10, umbra: 4 }),
  w('beholderScepter', 'Beholder Scepter', '👁️', 'scepter', 'arcane', { everwatchingEye: 3, umbralEye: 8 }, true),
  w('everwatchRepeater', 'Everwatch Repeater', '🔫', 'repeater', 'arcane', { everwatchingEye: 2, umbra: 6, darkClaw: 8 }, true),
  a('mothRobe', 'Mothsilk Robe', '👘', 'robe', { gloom: 10, shadowWisp: 4 }),
  a('crawlerPlate', 'Crawler Plate', '🛡️', 'heavy', { darkClaw: 12, umbra: 4 }),
  a('pearlShield', 'Pearl Shield', '🛡️', 'shield', { umbra: 8, umbralSlime: 6 }),
  x('eyeAmulet', 'Eye Amulet', '🧿', ['range'], { umbralEye: 8, gloom: 4 }),
  x('bandolier', 'Bandolier', '🎒', ['rate'], { gloom: 8, darkClaw: 6 }),
  x('abyssPearl', 'Abyssal Pearl', '🦪', ['gold'], { umbra: 6, umbralSlime: 6 }),
  w('gazingStaff', 'Gazing Staff', '👁️', 'staff', 'arcane', { umbralEye: 10, gloom: 4 }),
  w('crawlerCrossbow', 'Crawler Crossbow', '🎯', 'crossbow', 'physical', { darkClaw: 10, umbralSlime: 4 }),
  x('gloomsilkGloves', 'Gloomsilk Gloves', '🧤', ['crit'], { gloom: 8, shadowWisp: 4 }),

  // ---- Ember Mines ----
  ...at('caves'),
  w('impPistol', 'Imp Pistol', '🔫', 'pistol', 'fire', { demonBone: 8, demonWing: 4 }),
  w('magmaRifle', 'Magma Rifle', '🌋', 'rifle', 'fire', { magma: 10, chitin: 5 }),
  w('beetleRepeater', 'Beetle Repeater', '🪲', 'repeater', 'acid', { chitin: 10, ember: 4 }),
  w('hellfangDagger', 'Hellfang Dagger', '🗡️', 'dagger', 'fire', { demonTooth: 8, demonBone: 5 }),
  w('infernoBlade', 'Inferno Blade', '⚔️', 'sword', 'fire', { ember: 10, demonBone: 5 }),
  w('houndSpear', 'Hellhound Spear', '🔱', 'spear', 'fire', { demonTooth: 10, chitin: 4 }),
  w('forgeHammer', 'Forge Hammer', '🔨', 'hammer', 'fire', { chitin: 12, magma: 6 }),
  w('cinderBow', 'Cinder Bow', '🏹', 'shortbow', 'fire', { ember: 8, demonWing: 5 }),
  w('chitinCrossbow', 'Chitin Crossbow', '🎯', 'crossbow', 'physical', { chitin: 10, demonBone: 5 }),
  w('magmaWand', 'Magma Wand', '🪄', 'wand', 'fire', { magma: 8, ember: 4 }),
  w('salamanderStaff', 'Salamander Staff', '🦎', 'staff', 'fire', { ember: 10, magma: 5 }),
  w('demonTome', 'Demonic Tome', '📕', 'tome', 'fire', { demonWing: 10, demonBone: 5 }),
  w('lordScepter', "Demon Lord's Scepter", '🔥', 'scepter', 'decay', { forsakenSoul: 3, demonBone: 8 }, true),
  w('soulCleaver', 'Soul Cleaver', '🪓', 'glaive', 'decay', { forsakenSoul: 2, demonTooth: 10 }, true),
  a('impLeathers', 'Imp Leathers', '🧥', 'light', { demonWing: 10, chitin: 4 }),
  a('magmaPlate', 'Magma Plate', '🛡️', 'heavy', { magma: 10, demonBone: 6 }),
  a('hellShield', 'Hellforged Shield', '🛡️', 'shield', { demonBone: 10, chitin: 6 }),
  x('cinderRing', 'Cinder Ring', '💍', ['damage'], { ember: 8, demonTooth: 4 }),
  x('demonHorn', 'Demon Horn', '📯', [], { demonBone: 8, demonTooth: 4 }, 'demon'),
  x('minersLamp', "Miner's Lamp", '🪔', ['drops'], { chitin: 8, ember: 5 }),
  w('hellhoundGlaive', 'Hellhound Glaive', '🪓', 'glaive', 'fire', { demonTooth: 10, ember: 5 }),
  w('impFocus', 'Imp Focus', '👿', 'focus', 'fire', { demonWing: 8, magma: 5 }),
  a('cinderShroud', 'Cinder Shroud', '👘', 'robe', { ember: 10, demonWing: 5 }),
  x('chitinBracer', 'Chitin Bracer', '🛡️', ['stun'], { chitin: 8, demonBone: 4 }),

  // ---- Venom Caverns ----
  ...at('mines'),
  w('mithrilPistol', 'Mithril Pistol', '🔫', 'pistol', 'physical', { ore: 8, chitin: 4 }),
  w('drakeRifle', 'Drakeslayer Rifle', '🎯', 'rifle', 'fire', { scale: 10, ore: 5 }),
  w('venomRepeater', 'Venom Repeater', '🐍', 'repeater', 'poison', { scale: 8, ore: 6 }),
  w('mithrilDagger', 'Mithril Dagger', '🗡️', 'dagger', 'physical', { ore: 8, scale: 4 }),
  w('basiliskFang', 'Basilisk Fang', '🐍', 'dagger', 'poison', { scale: 8, demonTooth: 4 }),
  w('mithrilSword', 'Mithril Sword', '⚔️', 'sword', 'physical', { ore: 12, scale: 4 }),
  w('venomGlaive', 'Venom Glaive', '🪓', 'glaive', 'poison', { scale: 10, ore: 6 }),
  w('trollClub', 'Troll Club', '🏏', 'hammer', 'physical', { ore: 14, chitin: 4 }),
  w('koboldPike', 'Kobold Pike', '🔱', 'spear', 'physical', { ore: 10, demonBone: 4 }),
  w('drakeLongbow', 'Drake Longbow', '🏹', 'longbow', 'fire', { scale: 10, ember: 5 }),
  w('venomBow', 'Venom Bow', '🏹', 'shortbow', 'poison', { scale: 8, ore: 4 }),
  w('mithrilWand', 'Mithril Wand', '🪄', 'wand', 'arcane', { ore: 8, magma: 4 }),
  w('basiliskStaff', 'Basilisk Staff', '🐍', 'staff', 'poison', { scale: 10, ore: 5 }),
  w('drakeFocus', 'Drake-Eye Focus', '🐉', 'focus', 'fire', { scale: 10, ember: 6 }),
  w('deepTome', 'Tome of the Deep', '📘', 'tome', 'acid', { ore: 10, magma: 5 }),
  w('acidScepter', 'Acid Scepter', '🧪', 'scepter', 'acid', { scale: 8, magma: 6 }),
  w('wyrmfireStaff', 'Wyrmfire Staff', '🔥', 'staff', 'fire', { scale: 14, ore: 8 }, true),
  w('drakefangBlade', 'Drakefang Blade', '⚔️', 'sword', 'fire', { scale: 12, ore: 8 }, true),
  a('mithrilMail', 'Mithril Mail', '⛓️', 'heavy', { ore: 12, scale: 4 }),
  a('scaleLeathers', 'Drakescale Leathers', '🧥', 'light', { scale: 10, chitin: 4 }),
  a('venomRobe', 'Venomweave Robe', '👘', 'robe', { scale: 8, demonWing: 6 }),
  x('mithrilBand', 'Mithril Band', '💍', ['crit'], { ore: 8, scale: 4 }),
  x('dragonscaleCharm', 'Dragonscale Charm', '🐉', [], { scale: 10, ore: 4 }, 'dragon'),
  x('prospectorPick', "Prospector's Pick", '⛏️', ['gold'], { ore: 10, chitin: 4 }),
  w('koboldLongbow', 'Kobold Longbow', '🏹', 'longbow', 'physical', { ore: 10, scale: 4 }),
  w('trollMaul', 'Cave Troll Maul', '🔨', 'hammer', 'physical', { ore: 16, scale: 6 }, true),
  w('lavaPistol', 'Lava Pistol', '🔫', 'pistol', 'fire', { scale: 8, magma: 6 }),
  w('basiliskCrossbow', 'Basilisk Crossbow', '🎯', 'crossbow', 'poison', { scale: 10, ore: 5 }),
  a('basiliskShield', 'Basilisk Shield', '🛡️', 'shield', { scale: 10, ore: 6 }),
  a('koboldVest', 'Kobold Vest', '🧥', 'light', { ore: 10, chitin: 4 }),
  x('venomNecklace', 'Venom Fang Necklace', '📿', ['damage'], { scale: 8, ore: 6 }),

  // ---- Frost Peaks ----
  ...at('peaks'),
  w('iceShardPistol', 'Ice Shard Pistol', '🔫', 'pistol', 'frost', { frost: 8, fur: 4 }),
  w('glacierRepeater', 'Glacier Repeater', '❄️', 'repeater', 'frost', { frost: 10, ecto: 4 }),
  w('yetiHammer', 'Yeti Hammer', '🔨', 'hammer', 'frost', { fur: 14, frost: 6 }),
  w('icicleDagger', 'Icicle Dagger', '🗡️', 'dagger', 'frost', { frost: 8, fur: 4 }),
  w('iceWolfGlaive', 'Ice Wolf Glaive', '🪓', 'glaive', 'frost', { fur: 10, frost: 6 }),
  w('rimeSpear', 'Rime Spear', '🔱', 'spear', 'frost', { frost: 10, ecto: 4 }),
  w('frostLongbow', 'Frostbite Longbow', '🏹', 'longbow', 'frost', { fur: 10, frost: 5 }),
  w('snowdriftBow', 'Snowdrift Bow', '🏹', 'shortbow', 'physical', { fur: 8, frost: 4 }),
  w('glacialCrossbow', 'Glacial Crossbow', '🎯', 'crossbow', 'frost', { frost: 10, fur: 5 }),
  w('wraithWand', 'Wraith Wand', '👻', 'wand', 'decay', { ecto: 8, frost: 4 }),
  w('blizzardStaff', 'Blizzard Staff', '❄️', 'staff', 'frost', { frost: 12, ecto: 5 }),
  w('spiritTome', 'Tome of Spirits', '📗', 'tome', 'decay', { ecto: 10, fur: 5 }),
  w('auroraScepter', 'Aurora Scepter', '🌌', 'scepter', 'radiant', { frost: 10, ecto: 6 }),
  w('spectralBlade', 'Spectral Blade', '⚔️', 'sword', 'decay', { ecto: 10, frost: 5 }),
  w('winterRifle', "Winter's Edge Rifle", '🎯', 'rifle', 'frost', { frost: 14, ecto: 8, fur: 6 }, true),
  w('spriteFocus', 'Frost Sprite Focus', '🧊', 'focus', 'frost', { frost: 12, ecto: 8 }, true),
  a('yetiPelt', 'Yeti Pelt', '🧥', 'light', { fur: 12, frost: 4 }),
  a('glacierPlate', 'Glacier Plate', '🛡️', 'heavy', { frost: 12, fur: 6 }),
  a('wraithShroud', 'Wraith Shroud', '👘', 'robe', { ecto: 10, fur: 5 }),
  a('iceShield', 'Ice Shield', '🛡️', 'shield', { frost: 10, fur: 6 }),
  a('spiritMail', 'Spirit Mail', '⛓️', 'heavy', { ecto: 12, frost: 8 }, true),
  x('snowflakeBrooch', 'Snowflake Brooch', '❄️', ['stun'], { frost: 8, ecto: 4 }),
  x('furGloves', 'Wolf-Fur Gloves', '🧤', ['rate'], { fur: 8, frost: 4 }),
  x('ectoLantern', 'Ecto Lantern', '🏮', ['radius'], { ecto: 8, frost: 4 }),
  x('spiritWard', 'Spirit Ward', '🪬', [], { ecto: 10, fur: 4 }, 'undead'),
  w('frostTome', 'Tome of Frost', '📘', 'tome', 'frost', { frost: 12, fur: 4 }),
  w('yetiSpear', 'Yeti Spear', '🔱', 'spear', 'frost', { fur: 12, frost: 6 }),
  w('ectoFocus', 'Ectoplasm Focus', '🫧', 'focus', 'decay', { ecto: 10, frost: 4 }),
  w('frostWand', 'Frost Wand', '❄️', 'wand', 'frost', { frost: 8, fur: 4 }),
  w('glacierBlade', 'Glacier Blade', '⚔️', 'sword', 'frost', { frost: 12, fur: 6 }),
  a('iceWolfCoat', 'Ice Wolf Coat', '🧥', 'light', { fur: 12, ecto: 4 }),
  x('frostRing', 'Frost Ring', '💍', ['crit'], { frost: 8, fur: 4 }),

  // ---- Ascendant Steps ----
  ...at('cliffs'),
  w('harpyBow', 'Harpy Bow', '🏹', 'shortbow', 'physical', { plume: 8, skystone: 4 }),
  w('owlLongbow', 'Snow Owl Longbow', '🦉', 'longbow', 'physical', { plume: 10, skystone: 5 }),
  w('griffinCrossbow', 'Griffin Crossbow', '🎯', 'crossbow', 'physical', { plume: 10, skystone: 6 }),
  w('skyPistol', 'Sky Pistol', '🔫', 'pistol', 'lightning', { skystone: 8, plume: 4 }),
  w('wyvernRifle', 'Wyvern Rifle', '🎯', 'rifle', 'frost', { skystone: 10, plume: 5 }),
  w('galeRepeater', 'Gale Repeater', '🌬️', 'repeater', 'lightning', { plume: 10, skystone: 5 }),
  w('talonDagger', 'Talon Dagger', '🗡️', 'dagger', 'physical', { plume: 8, skystone: 4 }),
  w('skystoneSword', 'Skystone Sword', '⚔️', 'sword', 'lightning', { skystone: 10, plume: 4 }),
  w('giantHammer', "Giant's Hammer", '🔨', 'hammer', 'frost', { skystone: 14, plume: 4 }),
  w('wyvernGlaive', 'Wyvern Glaive', '🪓', 'glaive', 'frost', { skystone: 10, plume: 6 }),
  w('windWand', 'Wind Wand', '🪄', 'wand', 'lightning', { plume: 8, skystone: 4 }),
  w('cloudstoneFocus', 'Cloudstone Focus', '🔮', 'focus', 'lightning', { skystone: 10, plume: 5 }),
  w('featherTome', 'Tome of Feathers', '📘', 'tome', 'physical', { plume: 12, skystone: 4 }),
  w('ascendantScepter', 'Ascendant Scepter', '✨', 'scepter', 'radiant', { skystone: 10, plume: 6 }),
  w('pilgrimStaff', "Pilgrim's Staff", '🦯', 'staff', 'radiant', { skystone: 8, plume: 8 }),
  w('wyvernLance', 'Wyvern Lance', '🔱', 'spear', 'frost', { skystone: 14, plume: 8 }, true),
  w('giantslayerBow', 'Giantslayer Bow', '🏹', 'longbow', 'physical', { skystone: 14, plume: 10 }, true),
  a('owlCloak', 'Owl-Feather Cloak', '🧥', 'light', { plume: 10, skystone: 4 }),
  a('giantPlate', "Giant's Plate", '🛡️', 'heavy', { skystone: 12, plume: 4 }),
  a('windRobe', 'Windweave Robe', '👘', 'robe', { plume: 10, skystone: 5 }),
  a('skystoneShield', 'Skystone Shield', '🛡️', 'shield', { skystone: 10, plume: 6 }),
  a('ascendantRobe', 'Ascendant Vestments', '🥻', 'robe', { skystone: 12, plume: 10 }, true),
  x('featherCharm', 'Feather Charm', '🪶', ['rate'], { plume: 8, skystone: 4 }),
  x('skystoneRing', 'Skystone Ring', '💍', ['damage'], { skystone: 8, plume: 4 }),
  x('eagleEye', 'Eagle Eye', '🦅', ['range'], { plume: 8, skystone: 6 }),
  x('dragonTooth', "Dragon's Tooth", '🦷', [], { skystone: 10, plume: 6 }, 'dragon'),
  w('harpyClaw', 'Harpy Claw', '🗡️', 'dagger', 'lightning', { plume: 8, skystone: 6 }),
  w('owlWand', 'Owl Wand', '🦉', 'wand', 'frost', { plume: 8, skystone: 5 }),
  w('griffinTome', 'Tome of the Griffin', '📗', 'tome', 'physical', { plume: 12, skystone: 6 }),
  w('giantRifle', "Giant's Rifle", '🎯', 'rifle', 'physical', { skystone: 12, plume: 6 }),
  w('summitScepter', 'Summit Scepter', '✨', 'scepter', 'lightning', { skystone: 10, plume: 5 }),
  a('harpyRobe', 'Harpy Robe', '👘', 'robe', { plume: 12, skystone: 4 }),
  a('giantShield', "Giant's Shield", '🛡️', 'shield', { skystone: 12, plume: 6 }),
  x('summitCharm', 'Summit Charm', '🏔️', ['gold'], { skystone: 8, plume: 6 }),

  // ---- Cloud Fortress ----
  ...at('fortress'),
  w('stormBow', 'Storm Bow', '🏹', 'shortbow', 'lightning', { feather: 8, thunder: 4 }),
  w('thunderbirdLongbow', 'Thunderbird Longbow', '🦅', 'longbow', 'lightning', { feather: 10, thunder: 5 }),
  w('knightCrossbow', 'Sky Knight Crossbow', '🎯', 'crossbow', 'physical', { thunder: 10, feather: 5 }),
  w('voltPistol', 'Volt Pistol', '🔫', 'pistol', 'lightning', { thunder: 8, feather: 4 }),
  w('stormRifle', 'Storm Rifle', '🎯', 'rifle', 'lightning', { thunder: 10, feather: 6 }),
  w('valkyrieSpear', 'Valkyrie Spear', '🔱', 'spear', 'radiant', { feather: 10, thunder: 5 }),
  w('skyKnightSword', 'Sky Knight Sword', '⚔️', 'sword', 'lightning', { thunder: 10, feather: 4 }),
  w('boltDagger', 'Bolt Dagger', '🗡️', 'dagger', 'lightning', { thunder: 8, feather: 4 }),
  w('cloudcleaver', 'Cloudcleaver', '🪓', 'glaive', 'lightning', { thunder: 12, feather: 6 }),
  w('stormcallWand', 'Stormcall Wand', '🪄', 'wand', 'lightning', { thunder: 8, feather: 4 }),
  w('tempestStaff', 'Tempest Staff', '⚡', 'staff', 'lightning', { thunder: 12, feather: 5 }),
  w('cloudheartFocus', 'Cloudheart Focus', '☁️', 'focus', 'lightning', { feather: 10, thunder: 6 }),
  w('valkyrieScepter', 'Valkyrie Scepter', '👑', 'scepter', 'radiant', { feather: 10, thunder: 6 }),
  w('titanMaul', 'Titan Maul', '🔨', 'hammer', 'lightning', { thunder: 16, feather: 8 }, true),
  w('heavensTome', 'Tome of the Heavens', '📖', 'tome', 'radiant', { feather: 14, thunder: 8 }, true),
  w('titanRepeater', 'Storm Titan Repeater', '🔫', 'repeater', 'lightning', { thunder: 14, feather: 10 }, true),
  a('valkyrieMail', 'Valkyrie Mail', '⛓️', 'heavy', { thunder: 12, feather: 6 }),
  a('stormhide', 'Stormhide Leathers', '🧥', 'light', { feather: 10, thunder: 5 }),
  a('knightShield', 'Sky Knight Shield', '🛡️', 'shield', { thunder: 10, feather: 6 }),
  a('titanPlate', 'Titan Plate', '🛡️', 'heavy', { thunder: 16, feather: 10 }, true),
  x('thunderRing', 'Thunder Ring', '💍', ['crit'], { thunder: 8, feather: 4 }),
  x('featherCrown', 'Feather Crown', '👑', ['damage'], { feather: 10, thunder: 4 }),
  x('stormCharm', 'Storm Charm', '⚡', ['rate'], { thunder: 8, feather: 6 }),
  x('cloudPurse', 'Cloud Purse', '👛', ['gold'], { feather: 8, thunder: 6 }),
  x('skyWard', 'Skyward Ward', '🪬', [], { thunder: 10, feather: 6 }, 'elemental'),
  x('lightningRod', 'Lightning Rod', '🗼', ['range'], { thunder: 10, feather: 4 }),
  w('valkyrieBow', 'Valkyrie Bow', '🏹', 'shortbow', 'radiant', { feather: 10, thunder: 4 }),
  w('knightHammer', 'Sky Knight Hammer', '🔨', 'hammer', 'lightning', { thunder: 14, feather: 6 }),
  w('thunderbirdTome', 'Thunderbird Tome', '📘', 'tome', 'lightning', { feather: 12, thunder: 5 }),
  w('stormPistol', 'Storm Pistol', '🔫', 'pistol', 'lightning', { thunder: 10, feather: 5 }),
  w('cloudlingWand', 'Cloudling Wand', '☁️', 'wand', 'radiant', { feather: 8, thunder: 6 }),
  a('valkyrieRobe', 'Valkyrie Robe', '👘', 'robe', { feather: 12, thunder: 4 }),
  a('stormShield', 'Storm Shield', '🛡️', 'shield', { thunder: 12, feather: 6 }),
  x('titanBelt', 'Titan Belt', '🎗️', ['damage'], { thunder: 10, feather: 6 }),

  // ---- Meteor Field ----
  ...at('meteors'),
  w('cometBow', 'Comet Bow', '🏹', 'shortbow', 'radiant', { stardust: 8, meteor: 4 }),
  w('starfallLongbow', 'Starfall Longbow', '🌠', 'longbow', 'radiant', { stardust: 10, meteor: 5 }),
  w('meteorCrossbow', 'Meteor Crossbow', '🎯', 'crossbow', 'fire', { meteor: 10, stardust: 5 }),
  w('starPistol', 'Star Pistol', '🔫', 'pistol', 'radiant', { stardust: 8, meteor: 4 }),
  w('meteorRepeater', 'Meteor Repeater', '🔫', 'repeater', 'fire', { meteor: 10, stardust: 6 }),
  w('miteDagger', 'Rock Mite Dagger', '🗡️', 'dagger', 'physical', { meteor: 8, stardust: 4 }),
  w('cometGlaive', 'Comet Glaive', '🪓', 'glaive', 'fire', { meteor: 10, stardust: 6 }),
  w('sentinelSpear', 'Sentinel Spear', '🔱', 'spear', 'radiant', { stardust: 10, meteor: 5 }),
  w('meteorHammer', 'Meteor Hammer', '🔨', 'hammer', 'fire', { meteor: 14, stardust: 4 }),
  w('cometWand', 'Comet Wand', '🪄', 'wand', 'fire', { stardust: 8, meteor: 4 }),
  w('nebulaStaff', 'Nebula Staff', '🌌', 'staff', 'arcane', { stardust: 12, meteor: 5 }),
  w('starheartFocus', 'Starheart Focus', '⭐', 'focus', 'radiant', { stardust: 10, meteor: 6 }),
  w('cosmicTome', 'Cosmic Tome', '📘', 'tome', 'arcane', { stardust: 12, meteor: 4 }),
  w('eaterScepter', 'Star Eater Scepter', '🌑', 'scepter', 'void', { stardust: 16, meteor: 8 }, true),
  w('supernovaRifle', 'Supernova Rifle', '💥', 'rifle', 'fire', { meteor: 16, stardust: 10 }, true),
  w('starblade', 'Starblade', '⚔️', 'sword', 'radiant', { stardust: 14, meteor: 10 }, true),
  a('meteorPlate', 'Meteor Plate', '🛡️', 'heavy', { meteor: 12, stardust: 4 }),
  a('cometCloak', 'Comet Cloak', '🧥', 'light', { stardust: 10, meteor: 4 }),
  a('nebulaRobe', 'Nebula Robe', '👘', 'robe', { stardust: 12, meteor: 4 }),
  a('sentinelShield', 'Sentinel Shield', '🛡️', 'shield', { meteor: 10, stardust: 6 }),
  a('cosmicRobe', 'Cosmic Vestments', '🥻', 'robe', { stardust: 16, meteor: 8 }, true),
  x('starRing', 'Star Ring', '💍', ['damage'], { stardust: 8, meteor: 4 }),
  x('cometTail', 'Comet Tail', '🌠', ['rate'], { stardust: 8, meteor: 6 }),
  x('meteorCore', 'Meteor Core', '☄️', ['radius'], { meteor: 10, stardust: 4 }),
  x('astrolabe', 'Astrolabe', '🧭', ['range'], { meteor: 8, stardust: 6 }),
  x('stardustPouch', 'Stardust Pouch', '👝', ['drops'], { stardust: 10, meteor: 4 }),
  x('constellationCharm', 'Constellation Charm', '✨', ['crit'], { stardust: 10, meteor: 6 }),
  w('cometDagger', 'Comet Dagger', '🗡️', 'dagger', 'fire', { meteor: 8, stardust: 6 }),
  w('astralSword', 'Astral Sword', '⚔️', 'sword', 'radiant', { stardust: 12, meteor: 6 }),
  w('sentinelRifle', 'Sentinel Rifle', '🎯', 'rifle', 'radiant', { stardust: 12, meteor: 6 }),
  w('eaterRepeater', 'Star Eater Repeater', '🔫', 'repeater', 'void', { stardust: 14, meteor: 8 }),
  w('meteorStaff', 'Meteor Staff', '☄️', 'staff', 'fire', { meteor: 12, stardust: 6 }),
  w('stardustWand', 'Stardust Wand', '✨', 'wand', 'radiant', { stardust: 10, meteor: 4 }),
  a('sentinelPlate', 'Sentinel Plate', '🛡️', 'heavy', { meteor: 14, stardust: 6 }),
  a('starlitCloak', 'Starlit Cloak', '🧥', 'light', { stardust: 12, meteor: 6 }),
  x('mitePouch', 'Rock Mite Pouch', '👝', ['gold'], { meteor: 10, stardust: 4 }),

  // ---- Void Rift: the long final stretch, the biggest armory ----
  ...at('rift'),
  w('shadeBow', 'Shade Bow', '🏹', 'shortbow', 'void', { shade: 8, void: 4 }),
  w('riftLongbow', 'Riftwalker Longbow', '🏹', 'longbow', 'void', { void: 10, shade: 5 }),
  w('soulCrossbow', 'Soul Crossbow', '🎯', 'crossbow', 'decay', { soul: 8, shade: 6 }),
  w('voidPistol', 'Void Pistol', '🔫', 'pistol', 'void', { void: 8, shade: 4 }),
  w('lichRifle', 'Lich Rifle', '🎯', 'rifle', 'decay', { soul: 10, void: 5 }),
  w('abyssRepeater', 'Abyss Repeater', '🔫', 'repeater', 'void', { void: 14, shade: 10 }),
  w('horrorFang', "Horror's Fang", '🗡️', 'dagger', 'void', { void: 8, shade: 4 }),
  w('darkKnightSword', 'Dark Knight Sword', '⚔️', 'sword', 'decay', { soul: 10, void: 5 }),
  w('eternityBlade', 'Blade of Eternity', '⚔️', 'sword', 'radiant', { soul: 16, void: 10, shade: 8 }),
  w('chimeraGlaive', 'Chimera Glaive', '🪓', 'glaive', 'fire', { soul: 10, shade: 6 }),
  w('behemothHammer', 'Behemoth Hammer', '🔨', 'hammer', 'physical', { soul: 14, void: 6 }),
  w('wyrmSpear', 'Void Wyrm Spear', '🔱', 'spear', 'void', { void: 12, soul: 6 }),
  w('shadeWand', 'Shade Wand', '🪄', 'wand', 'void', { shade: 8, soul: 4 }),
  w('succubusFocus', 'Succubus Focus', '💋', 'focus', 'arcane', { soul: 10, shade: 6 }),
  w('watcherStaff', 'Watcher Staff', '👁️', 'staff', 'arcane', { void: 10, soul: 5 }),
  w('oblivionStaff', 'Oblivion Staff', '🌀', 'staff', 'void', { void: 16, soul: 8 }),
  w('riftTome', 'Tome of the Rift', '📓', 'tome', 'void', { void: 12, shade: 6 }),
  w('chronoScepter', 'Chrono Scepter', '⏳', 'scepter', 'arcane', { void: 16, soul: 10 }),
  a('shadeCloak', 'Shade Cloak', '🧥', 'light', { shade: 10, void: 4 }),
  a('darkKnightPlate', 'Dark Knight Plate', '🛡️', 'heavy', { soul: 12, void: 6 }),
  a('wyrmscaleArmor', 'Wyrmscale Armor', '🐉', 'heavy', { void: 14, soul: 8 }),
  a('riftShield', 'Rift Shield', '🛡️', 'shield', { void: 12, shade: 6 }),
  a('lichShroud', 'Lich Shroud', '👘', 'robe', { soul: 10, shade: 6 }),
  x('voidRing', 'Void Ring', '💍', ['crit'], { void: 8, soul: 4 }),
  x('soulAmulet', 'Soul Amulet', '📿', ['damage'], { soul: 10, void: 6 }),
  x('riftCompass', 'Rift Compass', '🧭', ['range'], { void: 8, shade: 6 }),
  x('chimeraHeart', 'Chimera Heart', '❤️‍🔥', ['rate'], { soul: 10, shade: 6 }),
  x('brokenHourglass', 'Broken Hourglass', '⌛', ['gold'], { void: 10, soul: 6 }),
  w('succubusWand', 'Succubus Wand', '💋', 'wand', 'arcane', { soul: 8, shade: 6 }),
  w('lichTome', 'Lich Tome', '📓', 'tome', 'decay', { soul: 12, void: 6 }),
  w('watcherFocus', 'Watcher Focus', '👁️', 'focus', 'void', { void: 12, shade: 6 }),
  w('chimeraBow', 'Chimera Bow', '🏹', 'shortbow', 'fire', { soul: 10, shade: 6 }),
  w('behemothSpear', 'Behemoth Spear', '🔱', 'spear', 'physical', { soul: 14, void: 6 }),
  a('succubusRobe', 'Succubus Robe', '👘', 'robe', { soul: 12, shade: 6 }),
  x('horrorEye', 'Eye of Horror', '👁️', ['range'], { void: 10, shade: 6 }),
] as const;

export type CatalogGearId = (typeof GEAR_CATALOG)[number]['id'];
